### ISSUE TITLE
Add network resource support to NetworkService

### ISSUE THREAD

**Issue by drbild** [xaptum/go-enf#4]
(Depends on #3 and #5)

A "network" is a ::/64 block inside a customer's ::/48 domain.  Add methods to the `NetworkService` for listing, getting, and creating networks.  The API currently does not support deleting a network.

- [x] List Networks
   Method signature:
   ```go
    func (s *NetworkService) ListNetworks(ctx context.Context, domain string) ([]*Network, *http.Response, error)`
    ```
    API endpoint:
    `GET /api/xcr/v2/domains/<domain_id>/nws`
    Response Format:
    ```json
    { "data" : [ {<network1>}, {<network2>} ],
      "pages" : {}
    }
    ```
    See `auth.go` for how to handle this response format.
    
- [x] Get Network
   Method signature:
   func (s *NetworkService) GetNetwork(ctx context.Context, domain string, network string) (*Network, *http.Response, error)`
    ```
    API endpoint:
    `GET /api/xcr/v2/domains/<domain_id>/nws/<network_id>`
    I'm not sure if this API endpoint exists.  Check with Venkat. If not, skip this one for now, but open an issue on xaptum/xcr to add this endpoint. 
    Response Format:
    ```json
    { "data" : [ {<network1>} ],
      "pages" : {}
    }
    ```
- [ ] CreateNetwork
   Method signature:
   func (s *NetworkService) GetNetwork(ctx context.Context, domain string) (*Network, *http.Response, error)`
    ```
    API endpoint:
    `POST /api/xcr/v2/domains/<domain_id>/nws`
    Response Format:
    ```json
    { "data" : [ {<network1>} ],
      "pages" : {}
    }
    ```

**Comment by dylanirlbeck** [comment]
@drbild When using cURL for the Get Network endpoint I'm not receiving any response, so I don't think it exists yet. 

How difficult would it be to implement this API method? I'm open to doing it myself if you can point me in the right direction.

**Comment by dylanirlbeck** [comment]
As a follow-up, Venkat informed me to use `GET /api/xcr/v2/news/<prefix>/<prefix_len>`  as the endpoint in my implementation, so I'll do that instead.

**Comment by drbild** [comment]
:+1:   

( I assume that "news" is a typo, should be "nws"
