### ISSUE TITLE
Typo in Error property of ErrorResponse struct in enf.go

### ISSUE THREAD

**Issue by dylanirlbeck** [xaptum/go-enf#7]
Typo occurs [here](https://github.com/xaptum/go-enf/blob/master/enf/enf.go)

**Comment by dylanirlbeck** [comment]
@drbild Is this intentional?

**Comment by drbild** [comment]
I think that is intentional, because I think that `Error` is a reserved word in Go.  `Errorr` isn't a great name --- so at some point we'll need to revisit the ErrorResponse structure.
